#!/bin/bash

# Get the current owner of the file
current_owner=$(stat -c %U hello)

# Check if the current owner is 'guillaume'
if [ "$current_owner" = "guillaume" ]; then
    chown betty "hello"
    echo "File owner changed to betty."
else
    echo "The file is not owned by guillaume. Owner not changed."
fi
